import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root',
})

export class InMemoryDataService implements  InMemoryDbService {

  public createDb() {
    const heroes = [
      { id: 1, name: 'Dr Nice', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 2, name: 'Narco', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 3, name: 'Bombasto', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 4, name: 'Celeritas', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 5, name: 'Magneta', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. CommodiLorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. CommodiLorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 6, name: 'RubberMan', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 7, name: 'Dynama', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 8, name: 'Dr IQ', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 9, name: 'Magma', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' },
      { id: 10, name: 'Tornado', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam' }
    ];
    const news = [
      { id: 1, heroId: 1, newsText: '1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 3, heroId: 10, newsText: '3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 2, heroId: 1, newsText: '2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 4, heroId: 2, newsText: '4 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 5, heroId: 3, newsText: '5 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 6, heroId: 4, newsText: '6 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 7, heroId: 4, newsText: '7 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 8, heroId: 4, newsText: '8 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 9, heroId: 6, newsText: '9 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 10, heroId: 2, newsText: '10 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 11, heroId: 1, newsText: '11 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 12, heroId: 3, newsText: '12 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 13, heroId: 4, newsText: '13 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 14, heroId: 5, newsText: '14 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 15, heroId: 1, newsText: '15 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 16, heroId: 8, newsText: '16 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 17, heroId: 4, newsText: '17 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 18, heroId: 6, newsText: '18 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 19, heroId: 4, newsText: '19 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '},
      { id: 20, heroId: 2, newsText: '20 Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, amet. Commodi ipsam aperiam fugit maiores necessitatibus minima eveniet fugiat facere reiciendis, tempora ducimus ullam cum dignissimos beatae cumque ut reprehenderit ad laboriosam, natus qui aliquid mollitia pariatur repudiandae. Recusandae aperiam '}
    ]
    return {heroes, news};
  }
}